version: '2'
services:
  web:
    image: node:10.15
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - .:/app/
    working_dir: /app
    envitment:
      NODE_ENV: dev
    command: "node index.js"